// PAPATYA - 7. gün: tam açmış çiçek (8 ince taç yaprağı)
//
//
const phase7 = {
  left: 156,
  width: 7,
  height: 150,
  radius: 4,
  rotate: -2,
  color: "#4CAF50",
  grayColor: "#9a9a9a",
  children: [
    {
      top: 35, //sol yaprak
      left: -25,
      width: 32,
      height: 7,
      radius: 8,
      rotate: 50,
      color: "#4CAF50",
      grayColor: "#9a9a9a",
      children: [
        {
          // yaprağın ucundaki küçük yaprakçık (yaprağın çocuğu)
          top: -5,
          left: 3,
          width: 20,
          height: 5,
          radius: 8,
          rotate: 30,
          color: "#4CAF50",
          grayColor: "#a8a8a8",
        },
        {
          // yaprağın ucundaki küçük yaprakçık (yaprağın çocuğu)
          top: 7,
          left: 3,
          width: 20,
          height: 5,
          radius: 8,
          rotate: -30,
          color: "#4CAF50",
          grayColor: "#9a9a9a",
        },
      ],
    },
    {
      top: 78, //sağ yaprak
      left: 10,
      width: 15,
      height: 4,
      radius: 8,
      rotate: -30,
      color: "#4CAF50",
      grayColor: "#9a9a9a",
    },
    {
      top: 100, //sağ alt yaprak
      left: -10,
      width: 15,
      height: 4,
      radius: 8,
      rotate: 50,
      color: "#4CAF50",
      grayColor: "#9a9a9a",
    },
    {
      // küçük çiçeğin sapı
      top: 60,
      left: 10,
      width: 7,
      height: 34,
      radius: 3,
      rotate: 35,
      color: "#4CAF50",
      grayColor: "#9a9a9a",
      children: [
        {
          top: -45,
          left: -15,
          width: 46,
          height: 46,
          color: "transparent",
          children: [
            {
              top: -4,
              left: 12,
              width: 14,
              height: 22,
              radius: 7,
              rotate: -5,
              color: "#dd5396",
              grayColor: "#b5b5b5",
            },
            {
              top: 8,
              left: 26,
              width: 14,
              height: 22,
              radius: 7,
              rotate: 72,
              color: "#dd5396",
              grayColor: "#b5b5b5",
            },
            {
              top: 24,
              left: 20,
              width: 14,
              height: 22,
              radius: 7,
              rotate: 144,
              color: "#dd5396",
              grayColor: "#b5b5b5",
            },
            {
              top: 24,
              left: 4,
              width: 14,
              height: 22,
              radius: 7,
              rotate: 216,
              color: "#dd5396",
              grayColor: "#b5b5b5",
            },
            {
              top: 8,
              left: -2,
              width: 14,
              height: 22,
              radius: 7,
              rotate: 288,
              color: "#dd5396",
              grayColor: "#b5b5b5",
            },
            {
              top: 15,
              left: 13,
              width: 16,
              height: 16,
              radius: 8,
              color: "#fdb818",
              grayColor: "#c9c9c9",
            },
          ],
        },
      ],
    },
    {
      //asıl çiçek
      top: -160,
      left: -75,
      width: 140,
      height: 140,
      color: "transparent",
      rotate: -10,
      children: [
        {
          //1 sol
          top: -10,
          left: 55,
          width: 10,
          height: 65,
          radius: 8,
          rotate: -9,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //1 sağ
          top: -11,
          left: 75,
          width: 10,
          height: 65,
          radius: 8,
          rotate: 10,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //1
          top: -14,
          left: 60,
          width: 20,
          height: 67,
          radius: 8,
          rotate: 1,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //2
          top: 1,
          left: 95,
          width: 20,
          height: 67,
          radius: 8,
          rotate: 45,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //2 sağ
          top: -5,
          left: 90,
          width: 10,
          height: 67,
          radius: 8,
          rotate: 40,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //2 sol
          top: 10,
          left: 105,
          width: 10,
          height: 67,
          radius: 8,
          rotate: 55,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //3
          top: 32,
          left: 110,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 90,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //3 sağ
          top: 40,
          left: 110,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 95,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //3 sol
          top: 25,
          left: 110,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 80,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //4
          top: 66,
          left: 100,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 135,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //4 sağ
          top: 55,
          left: 105,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 125,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //4 sol
          top: 70,
          left: 92,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 140,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //5
          top: 80,
          left: 62,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 180,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //5 sağ
          top: 77,
          left: 57,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 190,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //5 sol
          top: 75,
          left: 75,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 170,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //6
          top: 70,
          left: 20,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 225,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //6 sağ
          top: 70,
          left: 40,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 215,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //6 sol
          top: 55,
          left: 25,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 235,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //7
          top: 32,
          left: 10,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 270,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //7 sağ
          top: 22,
          left: 20,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 280,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //7 sol
          top: 42,
          left: 20,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 260,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //8
          top: -2,
          left: 28,
          width: 20,
          height: 76,
          radius: 8,
          rotate: 315,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //8 sağ
          top: 5,
          left: 27,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 305,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          //8 sol
          top: -5,
          left: 40,
          width: 10,
          height: 76,
          radius: 8,
          rotate: 325,
          color: "#dd5396",
          grayColor: "#b5b5b5",
        },
        {
          top: 53,
          left: 53,
          width: 34,
          height: 34,
          radius: 17,
          color: "#fdb818",
          grayColor: "#c9c9c9",
        },
      ],
    },
  ],
};

export default phase7;
